import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "PDF to Text Locally — Extract Text Without Upload",
  description:
    "Extract text from PDF files directly in your browser. Fast extraction from text-based PDFs. No upload, no signup, no watermark — completely private.",
  alternates: { canonical: "https://local2pdf.com/tools/pdf-to-text" },
  openGraph: {
  title: "PDF to Text Locally — Extract Text Without Upload",
    description:
      "Extract text from PDFs privately in your browser. No upload, no signup, no watermark.",
    url: "https://local2pdf.com/tools/pdf-to-text",
    type: "website",
  },
};

export default function PdfToTextLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify([
            {
              "@context": "https://schema.org",
              "@type": "SoftwareApplication",
              name: "Local2PDF — PDF to Text Extractor",
              description:
                "Extract text from PDF files locally in your browser. Fast and private. No upload, no signup, no watermark.",
              applicationCategory: "UtilitiesApplication",
              operatingSystem: "All",
              offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
              browserRequirements: "Requires JavaScript",
            },
            {
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: [
                {
                  "@type": "Question",
                  name: "Are my PDF files uploaded to Local2PDF servers?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "No. All text extraction happens entirely in your browser using local web APIs. Your files are never uploaded to our servers.",
                  },
                },
                {
                  "@type": "Question",
                  name: "Can I extract text from scanned PDFs?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "This tool extracts text from text-based PDFs (generated by software). Scanned documents without an embedded text layer will not produce output. Use an OCR tool for scanned documents.",
                  },
                },
                {
                  "@type": "Question",
                  name: "Is PDF text extraction free?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "Yes. Local2PDF is completely free. There is no signup, no watermark, and unlimited conversions.",
                  },
                },
                {
                  "@type": "Question",
                  name: "What output format does the text extractor use?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "The extracted text is displayed in the browser and can also be downloaded as a .txt plain-text file with page separators.",
                  },
                },
              ],
            },
            {
              "@context": "https://schema.org",
              "@type": "BreadcrumbList",
              itemListElement: [
                { "@type": "ListItem", position: 1, name: "Home", item: "https://local2pdf.com" },
                { "@type": "ListItem", position: 2, name: "PDF Tools", item: "https://local2pdf.com/pdf-tools" },
                { "@type": "ListItem", position: 3, name: "PDF to Text", item: "https://local2pdf.com/tools/pdf-to-text" },
              ],
            },
          ]),
        }}
      />
      {children}
    </>
  );
}
